{% set name = "sec-edgar-mcp" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '1.0.4').lstrip('v') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --no-cache-dir

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=61.0
  run:
    - python >=3.11
    - pip
    - requests >=2.31.0

test:
  imports:
    - sec_edgar_mcp

about:
  home: https://github.com/stefanoamorelli/sec-edgar-mcp
  summary: Open-source MCP server for the SEC EDGAR database
  description: |
    Provides access to SEC EDGAR database through a Model Context Protocol (MCP) server.
    Created by Stefano Amorelli.
    
    Note: This package will automatically install additional dependencies
    (mcp and edgartools) via pip during installation, as they are not 
    yet available on conda-forge.
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefano.amorelli
